### PR TITLE
adding code for lesson-1.2

### PR DESCRIPTION
**Pull request by badgerbadgers**
code submission for lesson-1.2

### CODE REVIEW

**Review by Estheryu991 — COMMENTED** [review]
Nice job! Did you understand the difference between exports and module exports?

**Comment by badgerbadgers** [comment]
Hello! I do not know the difference, I would love know and read any resources on this topic. Thank you!

**Comment by Estheryu991** [comment]
> the difference between exports and module exports?


> Module.exports is the object reference that gets returned from the require() calls, while  exports is not returned by require(). 

> When we want to export a single class/variable/function from one module to another module, we use module.exports way. 
- Example: Create two file badegerbadger.js and badger.js and export the Arithmetic class from badegerbadger.js to badger.js using module.exports method. Here, we have created a class Arithmetic and exported the whole class using module.exports.
Did you understand?

**Comment by badgerbadgers** [comment]
Yes one way is one file (badgerbadger.js) using module.export will export a single function/variable/etc to another (badger.js) that will export the whole class to badger.js. I have also researching this issue, there are some very good resources! [https://stackoverflow.com/questions/7137397/module-exports-vs-exports-in-node-js](https://stackoverflow.com/questions/7137397/module-exports-vs-exports-in-node-js)

**Pull request merged**
